### ISSUE TITLE
When loading a new Stencil file, old stencil(s) are still used until new option selected.

### ISSUE THREAD

**Issue by aus-betz** [danyill/oscd-stencil#21]
### Describe the bug
When a new stencil JSON file is uploaded, the old stencils remain in effect until a new menu is selected. I changed the plug in at the top to reload, but I assume simply selecting a new stencil application would also have the same effect. I haven't tested as such. 

### To Reproduce
Have a stencil selected and ready to select IEDs. Click the 'Open' button and load a new stencil JSON file. Select IEDs and apply stencil. The original version of the stencil will still be used.

### Expected behavior
When loading a new stencil file, it takes effect immediately.

### Screenshots
![image](https://github.com/user-attachments/assets/5debb3e8-71cb-4db2-99bb-5d3d3aff3f82)

### System
Windows, MS Edge Version 131.0.2903.99 (Official build) (64-bit)

**Comment by danyill** [comment]
Quite right - it should reset the window, and leave no application selected. Fix soon.

**Comment by danyill** [comment]
This should be fixed now - thanks for reporting - the distribution has been updated, you may need to do a refresh with Ctrl + F5
